### ISSUE TITLE
Keeping the theme up to date?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mundana-theme-jekyll#1]
Love this theme so switched to it from the Medium one. How can I make sure my install is always up to date?

Thanks!

**Comment by wowthemesnet** [comment]
I'll push an update within an hour!

**Comment by rahulkumarsingh73690** [comment]
Just tell @wowthemesnet  about New Features that needs in this theme.

**Comment by wowthemesnet** [comment]
@rahulkumarsingh73690, @GiacomoLaw uses Mediumish. Anyways, good advice for anyone who misght see it :)
