### ISSUE TITLE
Font change from Nunito

### ISSUE THREAD

**Issue by piyushpaliwal** [wowthemesnet/mundana-theme-jekyll#10]
Hi, one of the reasons which attracted me towards this theme was the font that was used on the headings and if I am not wrong, it was *Nunito*.

I want to understand why was this change made, is it a performance bottleneck? or something else. I am thinking of switching back to that font, however, would like to understand this first.

**Comment by wowthemesnet** [comment]
It's meant to replicate Medium's serif font in articles. There's nothing preventing anyone to apply their own fonts though.

**Comment by piyushpaliwal** [comment]
> It's meant to replicate Medium's serif font in articles. There's nothing preventing anyone to apply their own fonts though.

That was quick 😄 and thanks for the clarification!

**Comment by wowthemesnet** [comment]
No problemo :)
