### ISSUE TITLE
Liquid Exception: No repo name found

### ISSUE THREAD

**Issue by piyushpaliwal** [wowthemesnet/mundana-theme-jekyll#2]
Hi, I was trying to setup a new blog locally, when I try jekyll serve, this is the error that I am setting
```GitHub Metadata: Error processing value 'title':
Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/default.html
ERROR: YOUR SITE COULD NOT BE BUILT:
```
I tried adding the `repository:` tag in the `_config.yaml` file but unfortunately that does not work. Can you please help me out here?

**Comment by piyushpaliwal** [comment]
This had to do with my setup, managed to fix it. Apologies for opening up an issue which had nothing to do with your theme. 😃

**Comment by wowthemesnet** [comment]
No worries, glad all is good now!
