### ISSUE TITLE
Jekyll vs WordPress theme differences

### ISSUE THREAD

**Issue by piyushpaliwal** [wowthemesnet/mundana-theme-jekyll#3]
Hi, I am loving this theme, however, the Jekyll theme version looks like a really stripped down version as compared to the Wordpress one. Is there any possibility of getting the entire feature set available maybe as part of documentation so that we can choose what we like and strip the unwanted stuff.

Also, I understand that this is originally a paid theme for WordPress. I am willing to pay for this if the customizations can be provided for Jekyll as well.

**Comment by piyushpaliwal** [comment]
@wowthemesnet guys, can you please provide an update on this? Even an acknowledgment would work at this point

**Comment by wowthemesnet** [comment]
@piyushpaliwal , please check [latest version](https://github.com/wowthemesnet/mundana-theme-jekyll/releases/tag/1.0.12). 

For [live demo](https://wowthemesnet.github.io/mundana-theme-jekyll/) you might need to empty cache first.

Please, let me know if there are any more features you'd like (as long as they can be implemented in a static site).

**Comment by rahulkumarsingh73690** [comment]
Implement Tags in this template

**Comment by piyushpaliwal** [comment]
> @piyushpaliwal , please check [latest version](https://github.com/wowthemesnet/mundana-theme-jekyll/releases/latest).
> 
> For [live demo](https://wowthemesnet.github.io/mundana-theme-jekyll/) you might need to empty cache first.
> 
> Please, let me know if there are any more features you'd like (as long as they can be implemented in a static site).

Hey, thanks for the update. How can we make the highlight portion display a featured post? It should just take the first available featured post and add title, excerpt and an image. It would be a welcomed addition.

**Comment by wowthemesnet** [comment]
@rahulkumarsingh73690 - I have implemented `tags` per your request.

@piyushpaliwal - I have redesigned the highlighted post per your advice. Simply tag a post as `sticky` and it will be dynamically highlighted on homepage. [Post Example](https://raw.githubusercontent.com/wowthemesnet/mundana-theme-jekyll/master/_posts/2019-01-18-charm-old-cities.md).

_Frontend Output:_

![2019-04-02_14h51_54](https://user-images.githubusercontent.com/5597992/55400599-f657ac00-5556-11e9-9d9f-7d6e7fa9b0e8.png)

**Comment by piyushvarshney** [comment]
Hi there! Absolutely loved your theme.
How can we get Mundana WordPress theme like hover-to-search_box option where the box appears when we hover over the magnifying glass?
Please help!!

Wordpress reference:
[https://www.themepush.com/demo-mundana/museums-are-permanent-place-eternal-soul/](url)
