### ISSUE TITLE
Paginator Error 

### ISSUE THREAD

**Issue by dkarthe** [wowthemesnet/mundana-theme-jekyll#4]
Hi, 
Thanks for making this theme and I really loved it. Here I have to mention some issues related to paginator here are, I have set baiseurl to my custom domain and I was added more posts, if I click next page the pagination doesn't work properly, because it too take baseurl and additionally . it shows page error
![screenshot 144](https://user-images.githubusercontent.com/26917730/53428376-b0b43a80-3a10-11e9-9079-f7bf7f369e69.png) 
kindly tell me how to resolve this issue.

**Comment by wowthemesnet** [comment]
@dkarthe could you please show me your repository?

**Comment by dkarthe** [comment]
dkarthe/PD

**Comment by wowthemesnet** [comment]
Ok, I see what's going on there.
You are on root already so change this: 
https://github.com/dkarthe/PD/blob/master/_config.yml#L6

to this: 
```
baseurl: ''
```

(per guide: https://github.com/wowthemesnet/mundana-theme-jekyll#install-mundana)

**Comment by dkarthe** [comment]
I just want to give u small gift for you. fontawesome premium code.. provide me ur mail id i'll share with u

**Comment by dkarthe** [comment]
> Ok, I see what's going on there.
> You are on root already so change this:
> https://github.com/dkarthe/PD/blob/master/_config.yml#L6
> 
> to this:
> 
> ```
> baseurl: ''
> ```
> (per guide: https://github.com/wowthemesnet/mundana-theme-jekyll#install-mundana)

its work fine.. thanks

**Comment by wowthemesnet** [comment]
Thanks @dkarthe , my e-mail is wowthemesnet@gmail.com
