### ISSUE TITLE
Add a Headless CMS e.g Netlify or Forestry.

### ISSUE THREAD

**Issue by stephenajulu** [wowthemesnet/mundana-theme-jekyll#45]
Hi, how are you?
This is one of the best blogging theme i have ever seen.
But i have one issue. It doesn't have a backend for easier and cleaner write experience.
Kindly add this feature.

**Comment by DirtyF** [comment]
👋 Hey, you can [import this theme on Forestry](https://app.forestry.io/quick-start?repo=forestryio/jekyll-mundana-forestry&engine=jekyll) in a single click 😉

**Comment by stephenajulu** [comment]
thank you very much
