### ISSUE TITLE
Issue in Mobile View

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mundana-theme-jekyll#6]
Hello Sai,

Recently i installed this theme on my website its really amazing view in desktop but when I open my website from mobile then i see the text is not in right place means no padding. I suggest you to please check this theme in mobile also and fix this.

**Comment by piyushpaliwal** [comment]
Yup, this affects me as well. To narrow it down, it can be seen only in the post layouts.

**Comment by rahulkumarsingh73690** [comment]
This is serious problem please check @wowthemesnet

**Comment by rahulkumarsingh73690** [comment]
Finally Fixed Thanks.
