### ISSUE TITLE
New posts not showing up in the "All Stories" section

### ISSUE THREAD

**Issue by soham96** [wowthemesnet/mundana-theme-jekyll#84]
New posts I am making shows up in features, sticky and other areas, but not in the "All Stories" section. Weirdly, only example posts that you have made in your repo show up, but when I change their filename to a newer year, they do not show up. Could this be an issue with the year of the post?

**Comment by shairyar** [comment]
Running into the same issue, is there any solution to this?

**Comment by soham96** [comment]
Hi. I realised that the latest three posts will show up at the top of the page. Older posts will show up in the "All Stories" section. So you will start to see posts in the "All Stories" section if you have 4 or more posts.
